# .streamlit/config.toml

[theme]
base = "dark"
primaryColor = "#f63366"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"

[server]
headless = true
enableCORS = false
